### ISSUE TITLE
Reporte de Práctica #3

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-IsaHuerta23#2]
Reporte de Práctica - Diseño de TexBox personalizado con Visual Studio

[Reporte de Práctica #3.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-IsaHuerta23/files/6339508/Reporte.de.Practica.3.pdf)

**Comment by DuilioAquino10** [comment]
Calificacion 19.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
